name: Mirror on-chain proposals

on:
  repository_dispatch:
    types: [proposalCreated]

permissions:
  contents: read
  actions: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run mirror
        run: node mirror.js
        env:
          RELAY_KEY: ${{ secrets.RELAY_KEY }}