name: Submit approved LilProps on-chain

on:
  schedule:
    - cron: '*/1 * * * *'

permissions:
  contents: read
  actions: write

jobs:
  prop_submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Submit approved props
        run: node prop_submit.js
        env:
          SAFE_OWNER_KEY: ${{ secrets.SAFE_OWNER_KEY }}