name: Forward LilProps to main space

on:
  schedule:
    - cron: '*/1 * * * *'

permissions:
  contents: read
  actions: write

jobs:
  prop_forward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Forward pending props
        run: node prop_forward.js
        env:
          RELAY_KEY: ${{ secrets.RELAY_KEY }}