name: Relay snapshot votes on-chain

on:
  schedule:
    - cron: '*/1 * * * *'

permissions:
  contents: read
  actions: write

jobs:
  relay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run relay
        run: node relay.js
        env:
          SAFE_OWNER_KEY: ${{ secrets.SAFE_OWNER_KEY }}